name: Zig CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Zig
        uses: mlugg/setup-zig@v1
        with:
          zig-version: "latest"

      - run: zig build test
